### ISSUE TITLE
219: attempt to index global 'rage1' (a nil value)

### ISSUE THREAD

**Issue by Brenex** [PapaGuacamole/rageGUI#2]
Getting this error in the error console while it is running:

[ERROR:] object:<event handler function> function:<dispatchEventToFunctions>
         <[string "Script: Battlerage main"]:219: attempt to index global 'rage1' (a nil value)>

**Comment by Brenex** [comment]
I fixed a few things in the code. The rage1 issue and the syntax for checking for the presence of anitimer. Here is the new main script file:

https://www.hastebin.com/tofojidobo.lua

**Comment by PapaGuacamole** [comment]
Fixed in v1.9
